# Generated by Django 3.1.2 on 2021-01-06 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(db_index=True, help_text='Referencia única. Ej: dominios.csv', max_length=160)),
                ('evento', models.CharField(db_index=True, help_text='Tipo de evento. Ej: descarga', max_length=90)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('object_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-object_created'],
            },
        ),
    ]
