# Generated by Django 4.2.26 on 2026-01-04 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0002_alter_event_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token', 'used'], name='channels_te_token_fc9332_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('channel_type', models.CharField(choices=[('telegram', 'Telegram'), ('webpush', 'Web Push'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], editable=False, max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this channel is currently active for receiving notifications')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the channel has been verified (e.g., user confirmed via bot)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sent_at', models.DateTimeField(blank=True, help_text='Last time a notification was successfully sent', null=True)),
                ('last_error_at', models.DateTimeField(blank=True, help_text='Last time sending failed', null=True)),
                ('last_error_message', models.TextField(blank=True, help_text='Last error message if any')),
                ('error_count', models.PositiveIntegerField(default=0, help_text='Consecutive error count (reset on success)')),
                ('chat_id', models.BigIntegerField(help_text='Telegram chat ID for sending messages', unique=True)),
                ('username', models.CharField(blank=True, help_text='Telegram username if available', max_length=100)),
                ('first_name', models.CharField(blank=True, help_text='Telegram first name', max_length=100)),
                ('last_name', models.CharField(blank=True, help_text='Telegram last name', max_length=100)),
                ('parse_mode', models.CharField(choices=[('HTML', 'HTML'), ('Markdown', 'Markdown'), ('MarkdownV2', 'MarkdownV2')], default='HTML', help_text='Message formatting mode', max_length=20)),
                ('disable_preview', models.BooleanField(default=False, help_text='Disable link previews in messages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Channel',
                'verbose_name_plural': 'Telegram Channels',
                'indexes': [models.Index(fields=['user', 'is_active'], name='channels_te_user_id_efcd7b_idx'), models.Index(fields=['chat_id'], name='channels_te_chat_id_288685_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('channel_type', models.CharField(choices=[('telegram', 'Telegram'), ('webpush', 'Web Push'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('channel_id', models.PositiveIntegerField(help_text='ID of the specific channel (TelegramChannel.id, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('external_id', models.CharField(blank=True, help_text='External message ID (e.g., Telegram message_id)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='subscriptions.usernotification')),
            ],
            options={
                'verbose_name': 'Channel Delivery',
                'verbose_name_plural': 'Channel Deliveries',
                'indexes': [models.Index(fields=['status', 'channel_type'], name='channels_ch_status_e8dd99_idx'), models.Index(fields=['notification', 'status'], name='channels_ch_notific_e4063a_idx')],
                'unique_together': {('notification', 'channel_type', 'channel_id')},
            },
        ),
    ]
