# Generated by Django 4.2.26 on 2026-01-04 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, help_text='Telegram chat ID (guardado aunque no haya channel)')),
                ('direction', models.CharField(choices=[('in', 'Recibido'), ('out', 'Enviado')], db_index=True, max_length=10)),
                ('text', models.TextField(blank=True, help_text='Contenido del mensaje')),
                ('telegram_message_id', models.BigIntegerField(blank=True, help_text='ID del mensaje en Telegram', null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Update completo de Telegram (solo para mensajes entrantes)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, help_text='Canal vinculado (puede ser null si el usuario no está vinculado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='channels.telegramchannel')),
            ],
            options={
                'verbose_name': 'Telegram Message',
                'verbose_name_plural': 'Telegram Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chat_id', 'created_at'], name='channels_te_chat_id_30c269_idx'), models.Index(fields=['channel', 'created_at'], name='channels_te_channel_d5331b_idx')],
            },
        ),
    ]
