# Generated by Django 3.1.2 on 2020-10-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrante',
            name='zone',
            field=models.CharField(default='AR', help_text='Para identificar en el pais donde esta', max_length=10),
        ),
        migrations.AlterField(
            model_name='registrante',
            name='legal_uid',
            field=models.CharField(db_index=True, max_length=90),
        ),
        migrations.AlterUniqueTogether(
            name='registrante',
            unique_together={('legal_uid', 'zone')},
        ),
    ]
