# Generated by Django 3.1.2 on 2020-11-28 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrantes', '0004_registrantetag_tagforregistrante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrantetag',
            name='registrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='registrantes.registrante'),
        ),
        migrations.AlterField(
            model_name='registrantetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrantes', to='registrantes.tagforregistrante'),
        ),
    ]
