# Generated by Django 3.1.2 on 2020-11-18 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0002_zona_tz'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoZona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaEnGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='zonas.grupozona')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='zonas.zona')),
            ],
        ),
    ]
