# Generated by Django 3.1.2 on 2020-11-18 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0003_grupozona_zonaengrupo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zonaengrupo',
            unique_together={('grupo', 'zona')},
        ),
    ]
