# Generated by Django 3.1.2 on 2021-02-05 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mensajes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('texto', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeDestinado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[(mensajes.models.EstadoMensaje['CREATED'], 'Creado'), (mensajes.models.EstadoMensaje['READED'], 'Leido'), (mensajes.models.EstadoMensaje['DELETED'], 'Borrado')], db_index=True, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajes.mensaje')),
            ],
        ),
    ]
