# Generated by Django 3.1.2 on 2021-06-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='mensajedestinado',
            options={'ordering': ['-created']},
        ),
    ]
