# Generated by Django 3.1.2 on 2021-02-05 02:38

from django.db import migrations, models
import mensajes.models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_auto_20210204_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajedestinado',
            name='estado',
            field=models.CharField(choices=[(mensajes.models.EstadoMensaje['CREATED'], 'Creado'), (mensajes.models.EstadoMensaje['READED'], 'Leido'), (mensajes.models.EstadoMensaje['DELETED'], 'Borrado')], db_index=True, default='Creado', max_length=10),
        ),
    ]
