# Generated by Django 3.1.2 on 2020-11-26 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnss', '0002_auto_20201012_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dns',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='regex_dns',
        ),
        migrations.CreateModel(
            name='EmpresaRegexDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex_dns', models.CharField(blank=True, help_text='Experesion regular para encontrar los DNSs que le pertenecen', max_length=190, null=True, unique=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regexs', to='dnss.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='dns',
            name='empresa_regex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nameservers', to='dnss.empresaregexdomain'),
        ),
    ]
