# Generated by Django 3.1.2 on 2020-11-28 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dnss', '0003_auto_20201126_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='dns',
            name='object_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dns',
            name='object_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='object_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='object_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empresaregexdomain',
            name='object_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresaregexdomain',
            name='object_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
