# Generated by Django 3.1.2 on 2021-01-08 23:36

from django.db import migrations, models, transaction
import uuid


def gen_uuid(apps, schema_editor, model_real_name):
    MyModel = apps.get_model('dnss', model_real_name)
    while MyModel.objects.filter(uid__isnull=True).exists():
        with transaction.atomic():
            for row in MyModel.objects.filter(uid__isnull=True)[:1000]:
                row.uuid = uuid.uuid4()
                row.save(update_fields=['uid'])


def update_dns(apps, schema_editor):
    gen_uuid(apps, schema_editor, model_real_name='DNS')


def update_empresa(apps, schema_editor):
    gen_uuid(apps, schema_editor, model_real_name='Empresa')


def update_empresar(apps, schema_editor):
    gen_uuid(apps, schema_editor, model_real_name='EmpresaRegexDomain')


class Migration(migrations.Migration):

    dependencies = [
        ('dnss', '0005_auto_20201128_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='dns',
            name='uid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(update_dns, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='dns',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),

        migrations.AddField(
            model_name='empresa',
            name='uid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(update_empresa, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='empresa',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),

        migrations.AddField(
            model_name='empresaregexdomain',
            name='uid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(update_empresar, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='empresaregexdomain',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),

    ]
