# Generated by Django 4.2.26 on 2026-01-03 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('registered', 'Dominio Registerado'), ('renewed', 'Dominio Renovado'), ('expired', 'Dominio Expirado'), ('dropped', 'Dominio Caido'), ('dns_changed', 'DNS Cambiado'), ('registrant_changed', 'Registrante Cambiado')], db_index=True, max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('event_data', models.JSONField(default=dict, help_text='Additional data about the event')),
                ('processed', models.BooleanField(db_index=True, default=False, help_text='Whether notifications have been generated for this event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-last_event_at'],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_types', models.JSONField(default=list, help_text='List of event types to subscribe to: ["dropped", "registered", ...]')),
                ('delivery_mode', models.CharField(choices=[('immediate', 'Immediato'), ('daily', 'Mi resumen diario'), ('weekly', 'Mi resumen semanal')], default='immediate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.subscriptiontarget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='subscriptio_user_id_50396b_idx'), models.Index(fields=['delivery_mode'], name='subscriptio_deliver_687981_idx')],
                'unique_together': {('user', 'target')},
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.CharField(choices=[('single', 'Single Event'), ('digest', 'Digest')], default='single', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('event_data', models.JSONField(default=dict, help_text='Relevant data for display')),
                ('grouped_events', models.JSONField(default=list, help_text='List of event IDs if this is a digest')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('event_date', models.DateField(blank=True, help_text='Date of the event(s) for grouping', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, help_text='The event this notification is about (null for digests)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='subscriptions.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='subscriptio_user_id_f3585e_idx'), models.Index(fields=['user', 'created_at'], name='subscriptio_user_id_ddfe48_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['processed', 'event_type'], name='subscriptio_process_d8aa0c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['content_type', 'object_id'], name='subscriptio_content_7fb63b_idx'),
        ),
    ]
