# Generated by Django 4.2.26 on 2026-01-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('registered', 'Dominio Registrado'), ('renewed', 'Dominio Renovado'), ('expired', 'Dominio Expirado'), ('dropped', 'Dominio Caido'), ('dns_changed', 'DNS Cambiado'), ('registrant_changed', 'Registrante Cambiado')], db_index=True, max_length=50),
        ),
    ]
