# Generated by Django 3.1.2 on 2020-10-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambios', '0002_campocambio_uid_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campocambio',
            name='campo',
            field=models.CharField(db_index=True, max_length=240, null=True),
        ),
    ]
