# Generated by Django 3.1.2 on 2020-10-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambios', '0004_auto_20201014_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambiosdominio',
            name='have_changes',
            field=models.BooleanField(default=True),
        ),
    ]
