# Generated by Django 3.1.2 on 2020-10-12 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrantes', '0001_initial'),
        ('dnss', '0001_initial'),
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('registered', models.DateTimeField(blank=True, null=True)),
                ('changed', models.DateTimeField(blank=True, null=True)),
                ('expire', models.DateTimeField(blank=True, null=True)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('registrante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dominios', to='registrantes.registrante')),
                ('zona', models.ForeignKey(help_text='Lo que va al final y no es parte del dominio', on_delete=django.db.models.deletion.CASCADE, related_name='dominios', to='zonas.zona')),
            ],
        ),
        migrations.CreateModel(
            name='DNSDominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('dns', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dominios', to='dnss.dns')),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dnss', to='dominios.dominio')),
            ],
            options={
                'unique_together': {('dominio', 'dns', 'orden')},
            },
        ),
    ]
