# Generated by Django 3.1.2 on 2020-10-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0003_dominio_uid_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominio',
            name='changes_migrated',
            field=models.IntegerField(default=0),
        ),
    ]
