# Generated by Django 3.1.2 on 2020-10-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0002_zona_tz'),
        ('dominios', '0006_auto_20201014_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='nombre',
            field=models.CharField(db_index=True, help_text='Nombre solo sin la zona', max_length=240),
        ),
        migrations.AlterUniqueTogether(
            name='dominio',
            unique_together={('nombre', 'zona')},
        ),
    ]
