# Generated by Django 3.1.2 on 2020-10-17 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0007_auto_20201015_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominio',
            name='next_update_priority',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Next time I need to update the "priority"'),
        ),
        migrations.AddField(
            model_name='dominio',
            name='priority_to_update',
            field=models.IntegerField(default=0, help_text='How mamy important is to update this domain'),
        ),
    ]
