# Generated by Django 3.1.2 on 2020-10-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0008_auto_20201017_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominio',
            name='data_readed',
            field=models.DateField(blank=True, help_text='When this record was readad (having changes or not)', null=True),
        ),
    ]
