# Generated by Django 3.1.2 on 2020-10-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0009_dominio_data_readed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='data_readed',
            field=models.DateTimeField(blank=True, help_text='When this record was readad (having changes or not)', null=True),
        ),
    ]
