# Generated by Django 3.1.2 on 2020-11-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0010_auto_20201020_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreDominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=250)),
                ('priority', models.IntegerField(default=50)),
            ],
        ),
    ]
