# Generated by Django 3.1.2 on 2020-11-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0011_predominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predominio',
            name='dominio',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
